Revert "Add `git status` check to determine what's dirty."
This reverts commit 8513c0b09f8706683a4aa3f3b88b0536315d3b87.

diff --git a/.github/workflows/onPush.yml b/.github/workflows/onPush.yml
--- a/.github/workflows/onPush.yml
+++ b/.github/workflows/onPush.yml
@@ -3,7 +3,9 @@ name: On Push
 on:
   push:
     branches:
-      - bugfix/testingGitStatus
+      - master
+    tags:
+      - "[0-9]+.[0-9]+.[0-9]+"
 
 jobs:
   app_build:
@@ -58,8 +60,34 @@ jobs:
           VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
         run: ./gradlew assembleRelease
 
-      - name: Print `git status`
-        run: git status
+      - name: Archive Build
+        uses: actions/upload-artifact@v3
+        with:
+          path: ./**/*.apk
+
+      - name: Create Github Pre-Release
+        if: startsWith(github.ref, 'refs/tags/')
+        uses: softprops/action-gh-release@v0.1.15
+        with:
+          tag_name: ${{ steps.rel_number.outputs.version }}
+          body_path: ./app/build/outputs/changelogGithub
+          draft: false
+          prerelease: true
+          files: |
+            ./app/build/outputs/apk/full/release/app-full-release.apk
+            ./app/build/outputs/apk/minimal/release/app-minimal-release.apk
+            ./wear/build/outputs/apk/release/wear-release.apk
+            ./automotive/build/outputs/apk/full/release/automotive-full-release.apk
+            ./automotive/build/outputs/apk/minimal/release/automotive-minimal-release.apk
+            ./version.txt
+
+      - name: Deploy to Firebase
+        env:
+          KEYSTORE_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
+          KEYSTORE_ALIAS: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
+          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS_PASSWORD }}
+          VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
+        run: ./gradlew appDistributionUploadFullRelease
 
   play_publish:
     name: Play Publish
@@ -115,5 +143,23 @@ jobs:
           VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
         run: ./gradlew bundleRelease
 
-      - name: Print `git status`
-        run: git status
+      - name: Deploy to Playstore Internal
+        env:
+          KEYSTORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_FILE_PASSWORD }}
+          KEYSTORE_ALIAS: ${{ secrets.UPLOAD_KEYSTORE_ALIAS }}
+          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_ALIAS_PASSWORD }}
+          VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
+        run: |
+          ./gradlew :wear:publishReleaseBundle :app:publishReleaseBundle
+          ./gradlew :automotive:publishReleaseBundle || echo "Failed to publish Automotive!"
+
+      - name: Promote Internal to Beta
+        if: startsWith(github.event.ref, 'refs/tags/')
+        env:
+          KEYSTORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_FILE_PASSWORD }}
+          KEYSTORE_ALIAS: ${{ secrets.UPLOAD_KEYSTORE_ALIAS }}
+          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_ALIAS_PASSWORD }}
+          VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
+        run: |
+          ./gradlew :wear:promoteReleaseBundle :app:promoteReleaseBundle
+          ./gradlew :automotive:promoteReleaseBundle || echo "Failed to promote Automotive!"
