Detect missing lockfile update on CI (#5154)
* Add new Github Action job to detect missing update of lockfiles

* [TOREVERT] Bump version without bumping lockfiles

* Send Github PR comment

* Use proper env vars

* Update env var

* Multiline error message

* Escape command in comment

* Revisit ordering of Github Action jobs

* Try to use annotation to not manage the removal of the message

* Revert "[TOREVERT] Bump version without bumping lockfiles"

This reverts commit 5a1a0f0aa5b339a3a4074c0f7fc22d8bf116b42b.

* Remove the PR message

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -22,7 +22,35 @@ jobs:
       - name: Validate YAML
         run: yamllint --strict --format github .
 
+  lockfiles:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: ./.github/actions/setup-build-env
+        with:
+          mock-google-services: "true"
+
+      - name: Update lockfiles
+        run: ./gradlew alldependencies --write-locks
+
+      - name: Check for missing lockfiles update
+        run: |
+          if [[ $(git status --porcelain) ]]; then
+            echo $(git status --porcelain)
+            echo -e "\n❌ Uncommitted changes detected in the repository."
+            echo -e "🔍 It seems that the dependency lockfiles are outdated. Please update them by running:"
+            echo -e "   ./gradlew alldependencies --write-locks"
+            echo -e "   Then commit the updated lockfiles to your branch."
+            error_message="Dependency changes detected, but lockfiles are not updated. Run \`./gradlew alldependencies --write-locks\` and commit the changes."
+            echo "::error file=gradle/libs.versions.toml,line=1,title=⛔ Lockfile Update Required::${error_message}"
+            exit 1;
+          else
+            echo -e "\n✔️ All dependency lockfiles are up to date. No uncommitted changes detected."
+          fi
+
   ktlint:
+    needs: [yamllint, lockfiles]
     runs-on: ubuntu-latest
     permissions:
       security-events: write
@@ -44,28 +72,8 @@ jobs:
           sarif_file: "./"
           category: "KTlint"
 
-  unit_tests:
-    name: "Unit Tests"
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - uses: ./.github/actions/setup-build-env
-        with:
-          mock-google-services: "true"
-
-      - name: Run test
-        run: ./gradlew :common:testDebugUnitTest # Should be adapted once we have more than one tests
-
-      - name: Upload test results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Unit test results
-          path: |
-            **/build/test-results/**/TEST-*.xml
-
   lint:
+    needs: [yamllint, lockfiles]
     runs-on: ubuntu-latest
     permissions:
       security-events: write
@@ -94,6 +102,7 @@ jobs:
           category: "Android Lint"
 
   pr_build:
+    needs: [yamllint, lockfiles]
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -134,8 +143,31 @@ jobs:
         with:
           path: ./**/*.apk
 
+  unit_tests:
+    name: "Unit Tests"
+    needs: [lint, lockfiles, ktlint]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: ./.github/actions/setup-build-env
+        with:
+          mock-google-services: "true"
+
+      - name: Run test
+        run: ./gradlew :common:testDebugUnitTest # Should be adapted once we have more than one tests
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: Unit test results
+          path: |
+            **/build/test-results/**/TEST-*.xml
+
   instrumentation_test:
     name: "Instrumentation Tests"
+    needs: [lint, lockfiles, ktlint]
     runs-on: ubuntu-latest
     strategy:
       # We want the result of each device to be reported, so we can't fail-fast
